name: Build backend server

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - 'backend/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  release-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Appease Docker's moronic repo name restriction
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.OWNER_LC }}/backend:${{ github.sha }} ./backend

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ env.OWNER_LC  }}/backend:${{ github.sha }}
