name: PR checks

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  test-cargo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            backend/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run tests
        working-directory: backend
        run: cargo test --verbose